[package]
name = "waku-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2"
libp2p = "0.43.0"
sha2 = "0.10.2"

[build-dependencies]
protoc-rust = "2"